issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: 'starrcmd/'
      linters:
        - nonamedreturns
    - path: '(.+)_test\.go'
      linters:
        - gochecknoglobals
        - forcetypeassert
        - funlen
        - lll
        - maintidx # uhg.

linters:
  enable-all: true
  disable:
    # deprecated
    - tenv
    # unused
    - tagliatelle
    - exhaustruct
    - dupl
    - nlreturn
    - musttag

linters-settings:
  ireturn:
    allow: [generic,stdlib,error]
# One day we'll fix all the field alignments. Anyone got a tool that just does it?
#  govet:
#    enable:
#    - fieldalignment
  depguard:
    rules:
      main:
        files:
        - $all
        allow:
        - $gostd
        - github.com/stretchr/testify
        - golift.io/starr
        - golang.org/x/net

run:
  timeout: 5m

output:
  sort-results: true
