issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude funlen for testing files.
    - linters:
        - nonamedreturns
      path: 'starrcmd/'
    - linters:
        - gochecknoglobals
        - forcetypeassert
        - funlen
        - lll
        - maintidx # uhg.
      path: '(.+)_test\.go'
    - linters:
        - lll
      path: 'starrtest/'

linters:
  enable-all: true
  disable:
    # deprecated
    - maligned
    - scopelint
    - interfacer
    - golint
    - ifshort
    - deadcode
    - nosnakecase
    - structcheck
    - varcheck
    # unused
    - tagliatelle
    - exhaustivestruct
    - exhaustruct
    - dupl
    - nlreturn
    - tagalign
    - depguard
    - musttag
    - perfsprint # need to fix these
    - testifylint # fix these too

# One day we'll fix all the field alignments. Anyone got a tool that just does it?
#linters-settings:
#  govet:
#    enable:
#      - fieldalignment

run:
  timeout: 5m
