issues:
  exclude-rules:
    # Exclude funlen for testing files.
    - linters:
        - nonamedreturns
      path: 'starrcmd/'
    - linters:
        - gochecknoglobals
        - forcetypeassert
        - funlen
        - maintidx # uhg.
      path: '(.+)_test\.go'
    - linters:
        - lll
      path: 'starrtest/'

linters:
  enable-all: true
  disable:
    # deprecated
    - maligned
    - scopelint
    - interfacer
    - golint
    - ifshort
    - deadcode
    - nosnakecase
    - structcheck
    - varcheck
    # unused
    - tagliatelle
    - exhaustivestruct
    - exhaustruct
    - dupl
    - nlreturn

#linters-settings:
#  govet:
#    enable:
#      - fieldalignment

run:
  timeout: 35m