issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    # Exclude funlen for testing files.
    - linters:
        - nonamedreturns
      path: 'starrcmd/'
    - linters:
        - gochecknoglobals
        - forcetypeassert
        - funlen
        - lll
        - maintidx # uhg.
      path: '(.+)_test\.go'
    - linters:
        - lll
      path: 'starrtest/'

linters:
  enable-all: true
  disable:
    # deprecated
    - gomnd
    - execinquery
    # unused
    - tagliatelle
    - exhaustruct
    - dupl
    - nlreturn
    - musttag
    # fix these so they work
    - tagalign

linters-settings:
# One day we'll fix all the field alignments. Anyone got a tool that just does it?
#  govet:
#    enable:
#      - fieldalignment
   depguard:
     rules:
       main:
        files:
          - $all
        allow:
          - $gostd
          - github.com/stretchr/testify

run:
  timeout: 5m
