issues:
  exclude-rules:
    # Exclude funlen for testing files.
    - linters:
        - nonamedreturns
      path: 'starrcmd/'
    - linters:
        - forcetypeassert
        - funlen
        - maintidx # uhg.
      path: '(.+)_test\.go'

linters:
  enable-all: true
  disable:
    # deprecated
    - maligned
    - scopelint
    - interfacer
    - golint
    - ifshort
    # unused
    - tagliatelle
    - exhaustivestruct
    - exhaustruct
    - dupl
    - nlreturn

run:
  timeout: 35m