name: test-and-lint
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
        with:
          skip: .git
  nopollution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: no cross pollution
        run: make nopollution
  # Runs `go test` against 3 operating systems.
  gotest:
    strategy:
      matrix:
        os: [macos, windows, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable
      - name: go-test
        run: go test -race -v -covermode=atomic  ./...
  # Runs golangci-lint on macos against freebsd and macos.
  golangci-darwin:
    strategy:
      matrix:
        os: [darwin, freebsd]
    name: golangci-lint
    runs-on: macos-latest
    env:
      GOOS: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.13.2
  # Runs golangci-lint on linux against linux and windows.
  golangci-linux:
    strategy:
      matrix:
        os: [windows, linux]
    name: golangci-lint
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.13.2
